// frontend/src/products.js
export const products = [
  // 1–10 Electronics
  { product_id: 1, product_name: "Wireless Mouse", brand: "Logitech", final_price: 599, main_image: "/images/mouse.png", description: "Ergonomic wireless mouse with adjustable DPI and long battery life.", category: "Electronics", rating: 4.8, reviewCount: 215, badge: "Bestseller" },
  { product_id: 2, product_name: "Mechanical Keyboard", brand: "Corsair", final_price: 1999, main_image: "/images/keyboard.png", description: "RGB mechanical keyboard with high responsiveness and durable keys.", category: "Electronics", rating: 4.7, reviewCount: 180 },
  { product_id: 3, product_name: "USB-C Hub", brand: "Anker", final_price: 1299, main_image: "/images/hub.png", description: "Multiport USB-C hub supporting HDMI, USB, and SD card slots.", category: "Electronics", rating: 4.6, reviewCount: 302, badge: "New" },
  { product_id: 4, product_name: "Noise Cancelling Headphones", brand: "Sony", final_price: 4999, main_image: "/images/headphones.png", description: "Premium headphones with active noise cancellation and long battery life.", category: "Electronics", rating: 4.9, reviewCount: 450, badge: "Bestseller" },
  { product_id: 5, product_name: "Webcam HD", brand: "Logitech", final_price: 2199, main_image: "/images/webcam.png", description: "Full HD webcam for streaming and video calls with clear image quality.", category: "Electronics", rating: 4.5, reviewCount: 250 },
  { product_id: 6, product_name: "Gaming Chair", brand: "DXRacer", final_price: 9999, main_image: "/images/gamingchair.png", description: "Ergonomic gaming chair with adjustable height and lumbar support.", category: "Electronics", rating: 4.7, reviewCount: 95 },
  { product_id: 7, product_name: "Smartwatch", brand: "Apple", final_price: 3499, main_image: "/images/smartwatch.png", description: "Apple smartwatch with fitness tracking, notifications, and health monitoring.", category: "Electronics", rating: 4.8, reviewCount: 310 },
  { product_id: 8, product_name: "Portable SSD 1TB", brand: "Samsung", final_price: 6499, main_image: "/images/ssd.png", description: "High-speed external SSD for fast file transfers and storage.", category: "Electronics", rating: 4.9, reviewCount: 199 },
  { product_id: 9, product_name: "Laptop Stand", brand: "Nulaxy", final_price: 899, main_image: "/images/laptopstand.png", description: "Adjustable laptop stand for comfortable typing and cooling.", category: "Electronics", rating: 4.4, reviewCount: 512, badge: "Sale" },
  { product_id: 10, product_name: "Wireless Earbuds", brand: "JBL", final_price: 2999, main_image: "/images/earbuds.png", description: "Compact wireless earbuds with high-quality sound and long battery life.", category: "Electronics", rating: 4.6, reviewCount: 288 },

  // 11–20 Electronics & Accessories
  { product_id: 11, product_name: "Action Camera", brand: "GoPro", final_price: 4599, main_image: "/images/actioncamera.png", description: "Durable action camera for capturing high-quality outdoor videos.", category: "Electronics", rating: 4.7, reviewCount: 155 },
  { product_id: 12, product_name: "LED Desk Lamp", brand: "BenQ", final_price: 799, main_image: "/images/desklamp.png", description: "Energy-efficient LED desk lamp with adjustable brightness.", category: "Home", rating: 4.5, reviewCount: 430 },
  { product_id: 13, product_name: "Bluetooth Speaker", brand: "Bose", final_price: 1999, main_image: "/images/speaker.png", description: "Portable Bluetooth speaker with clear sound and deep bass.", category: "Electronics", rating: 4.8, reviewCount: 290 },
  { product_id: 14, product_name: "Graphic Tablet", brand: "Wacom", final_price: 3999, main_image: "/images/tablet.png", description: "Professional graphic tablet for digital drawing and design.", category: "Electronics", rating: 4.6, reviewCount: 120 },
  { product_id: 15, product_name: "VR Headset", brand: "Oculus", final_price: 7999, main_image: "/images/vrheadset.png", description: "Immersive virtual reality headset for gaming and media.", category: "Electronics", rating: 4.7, reviewCount: 110, badge: "New" },
  { product_id: 16, product_name: "Smartphone Gimbal", brand: "DJI", final_price: 2999, main_image: "/images/gimbal.png", description: "Stabilizing gimbal for smooth smartphone video recording.", category: "Electronics", rating: 4.5, reviewCount: 99 },
  { product_id: 17, product_name: "External Monitor 24\"", brand: "Dell", final_price: 7999, main_image: "/images/monitor.png", description: "24-inch Full HD monitor for home and office use.", category: "Electronics", rating: 4.6, reviewCount: 240 },
  { product_id: 18, product_name: "Microphone USB", brand: "Blue", final_price: 1499, main_image: "/images/microphone.png", description: "High-quality USB microphone for streaming and recording.", category: "Electronics", rating: 4.8, reviewCount: 350 },
  { product_id: 19, product_name: "Fitness Tracker", brand: "Fitbit", final_price: 2199, main_image: "/images/fitnesstracker.png", description: "Track your steps, heart rate, and sleep patterns with ease.", category: "Fitness", rating: 4.4, reviewCount: 480 },
  { product_id: 20, product_name: "Wireless Charger", brand: "Anker", final_price: 999, main_image: "/images/charger.png", description: "Fast wireless charger compatible with multiple devices.", category: "Electronics", rating: 4.5, reviewCount: 600, badge: "Bestseller" },

  // 21–40 Home & Kitchen
  { product_id: 21, product_name: "Smart LED Bulb", brand: "Philips", final_price: 1299, main_image: "/images/ledbulb.png", description: "Smart bulb with color changing and voice control.", category: "Home", rating: 4.6, reviewCount: 320 },
  { product_id: 22, product_name: "Electric Kettle", brand: "Philips", final_price: 1599, main_image: "/images/kettle.png", description: "1.7L electric kettle with auto shut-off feature.", category: "Home", rating: 4.7, reviewCount: 280 },
  { product_id: 23, product_name: "Yoga Mat", brand: "Reebok", final_price: 799, main_image: "/images/yogamat.png", description: "Non-slip yoga mat for home and gym exercises.", category: "Fitness", rating: 4.5, reviewCount: 550 },
  { product_id: 24, product_name: "Air Purifier", brand: "Xiaomi", final_price: 4999, main_image: "/images/airpurifier.png", description: "Removes dust, pollen, and allergens for cleaner air.", category: "Home", rating: 4.6, reviewCount: 190 },
  { product_id: 25, product_name: "Blender", brand: "NutriBullet", final_price: 2999, main_image: "/images/blender.png", description: "High-speed blender for smoothies and shakes.", category: "Home", rating: 4.8, reviewCount: 410 },
  { product_id: 26, product_name: "Coffee Maker", brand: "DeLonghi", final_price: 3999, main_image: "/images/coffeemaker.png", description: "Automatic coffee maker with programmable timer.", category: "Home", rating: 4.5, reviewCount: 150 },
  { product_id: 27, product_name: "Vacuum Cleaner", brand: "Dyson", final_price: 8999, main_image: "/images/vacuum.png", description: "Powerful vacuum cleaner with HEPA filter and cordless operation.", category: "Home", rating: 4.9, reviewCount: 210 },
  { product_id: 28, product_name: "Air Fryer", brand: "Philips", final_price: 4999, main_image: "/images/airfryer.png", description: "Healthy air fryer with multiple cooking presets.", category: "Home", rating: 4.7, reviewCount: 380, badge: "Bestseller" },
  { product_id: 29, product_name: "Rice Cooker", brand: "Panasonic", final_price: 2499, main_image: "/images/ricecooker.png", description: "Cook perfect rice every time with smart cooking programs.", category: "Home", rating: 4.6, reviewCount: 140 },
  { product_id: 30, product_name: "Induction Cooktop", brand: "Prestige", final_price: 3299, main_image: "/images/induction.png", description: "Fast induction cooktop with temperature control.", category: "Home", rating: 4.4, reviewCount: 230 },

  // 31–40 Fashion
  { product_id: 31, product_name: "Leather Wallet", brand: "Fossil", final_price: 1599, main_image: "/images/wallet.png", description: "Genuine leather wallet with multiple compartments.", category: "Fashion", rating: 4.7, reviewCount: 300 },
  { product_id: 32, product_name: "Sunglasses", brand: "Ray-Ban", final_price: 2499, main_image: "/images/sunglasses.png", description: "UV-protected stylish sunglasses for men and women.", category: "Fashion", rating: 4.8, reviewCount: 250 },
  { product_id: 33, product_name: "Sports Shoes", brand: "Nike", final_price: 4999, main_image: "/images/shoes.png", description: "Comfortable and durable sports shoes for running.", category: "Fashion", rating: 4.6, reviewCount: 450 },
  { product_id: 34, product_name: "Backpack", brand: "Herschel", final_price: 2999, main_image: "/images/backpack.png", description: "Spacious backpack with padded laptop compartment.", category: "Fashion", rating: 4.7, reviewCount: 380 },
  { product_id: 35, product_name: "Wristwatch", brand: "Fossil", final_price: 3999, main_image: "/images/watch.png", description: "Analog wristwatch with leather strap and classic design.", category: "Fashion", rating: 4.5, reviewCount: 180 },
  { product_id: 36, product_name: "Cap", brand: "Adidas", final_price: 799, main_image: "/images/cap.png", description: "Stylish unisex cap for outdoor use.", category: "Fashion", rating: 4.4, reviewCount: 290 },
  { product_id: 37, product_name: "Belt", brand: "Levi's", final_price: 1299, main_image: "/images/belt.png", description: "Durable leather belt with adjustable buckle.", category: "Fashion", rating: 4.6, reviewCount: 160 },
  { product_id: 38, product_name: "Handbag", brand: "Michael Kors", final_price: 6999, main_image: "/images/handbag.png", description: "Fashionable handbag with spacious interior.", category: "Fashion", rating: 4.8, reviewCount: 110 },
  { product_id: 39, product_name: "Perfume", brand: "Calvin Klein", final_price: 3499, main_image: "/images/perfume.png", description: "Long-lasting fragrance for men and women.", category: "Fashion", rating: 4.7, reviewCount: 220 },
  { product_id: 40, product_name: "Scarf", brand: "Gucci", final_price: 4999, main_image: "/images/scarf.png", description: "Luxury scarf made from soft wool and silk.", category: "Fashion", rating: 4.9, reviewCount: 80 },

  // 41–50 Fitness & Outdoors
  { product_id: 41, product_name: "Treadmill", brand: "PowerMax", final_price: 24999, main_image: "/images/treadmill.png", description: "Motorized treadmill with multiple speed settings.", category: "Fitness", rating: 4.5, reviewCount: 60 },
  { product_id: 42, product_name: "Dumbbell Set", brand: "Bowflex", final_price: 8999, main_image: "/images/dumbbells.png", description: "Adjustable dumbbell set for strength training.", category: "Fitness", rating: 4.8, reviewCount: 130 },
  { product_id: 43, product_name: "Exercise Bike", brand: "Horizon", final_price: 15999, main_image: "/images/exercisebike.png", description: "Stationary bike with resistance levels and LCD display.", category: "Fitness", rating: 4.6, reviewCount: 90 },
  { product_id: 44, product_name: "Resistance Bands", brand: "Fit Simplify", final_price: 999, main_image: "/images/resistancebands.png", description: "Set of resistance bands for home workouts.", category: "Fitness", rating: 4.7, reviewCount: 700, badge: "Bestseller" },
  { product_id: 45, product_name: "Foam Roller", brand: "TriggerPoint", final_price: 1499, main_image: "/images/foamroller.png", description: "Foam roller for muscle relaxation and recovery.", category: "Fitness", rating: 4.5, reviewCount: 400 },
  { product_id: 46, product_name: "Skipping Rope", brand: "Reebok", final_price: 499, main_image: "/images/skippingrope.png", description: "Durable skipping rope for cardio workouts.", category: "Fitness", rating: 4.4, reviewCount: 650 },
  { product_id: 47, product_name: "Kettlebell", brand: "Amazon Basics", final_price: 2499, main_image: "/images/kettlebell.png", description: "Cast iron kettlebell for strength and conditioning.", category: "Fitness", rating: 4.7, reviewCount: 320 },
  { product_id: 48, product_name: "Pull-Up Bar", brand: "Iron Gym", final_price: 1499, main_image: "/images/pullupbar.png", description: "Doorway pull-up bar for upper body workouts.", category: "Fitness", rating: 4.3, reviewCount: 480 },
  { product_id: 49, product_name: "Yoga Block", brand: "Gaiam", final_price: 399, main_image: "/images/yogablock.png", description: "Foam yoga block to support poses and stretches.", category: "Fitness", rating: 4.6, reviewCount: 510 },
  { product_id: 50, product_name: "Exercise Mat", brand: "Amazon Basics", final_price: 699, main_image: "/images/exercisemat.png", description: "Cushioned mat for yoga, pilates, and workouts.", category: "Fitness", rating: 4.5, reviewCount: 800 },

  // 51–56 Electronics & Gadgets
  { product_id: 51, product_name: "Smartphone", brand: "Samsung", final_price: 19999, main_image: "/images/smartphone.png", description: "Latest Samsung smartphone with high-resolution camera.", category: "Electronics", rating: 4.6, reviewCount: 180 },
  { product_id: 52, product_name: "Tablet", brand: "Apple", final_price: 34999, main_image: "/images/tablet2.png", description: "iPad with Retina display and Apple Pencil support.", category: "Electronics", rating: 4.8, reviewCount: 220 },
  { product_id: 53, product_name: "Laptop", brand: "Dell", final_price: 54999, main_image: "/images/laptop2.png", description: "High-performance laptop for work and gaming.", category: "Electronics", rating: 4.7, reviewCount: 140 },
  { product_id: 54, product_name: "Smart Home Camera", brand: "Nest", final_price: 7999, main_image: "/images/homecamera.png", description: "Security camera with motion detection and cloud storage.", category: "Electronics", rating: 4.5, reviewCount: 190, badge: "Sale" },
  { product_id: 55, product_name: "Power Bank 20000mAh", brand: "Anker", final_price: 2499, main_image: "/images/powerbank.png", description: "High-capacity power bank for charging devices on-the-go.", category: "Electronics", rating: 4.8, reviewCount: 900, badge: "Bestseller" },
  { product_id: 56, product_name: "Smart Doorbell", brand: "Ring", final_price: 9999, main_image: "/images/doorbell.png", description: "Video doorbell with two-way communication and alerts.", category: "Electronics", rating: 4.6, reviewCount: 160 }
];